---
title: "EDA"
format: html
editor: visual
---

## Reading in Data and Converting Variables

```{r}
library(tidyverse)
library(tidyr)

data<-read.csv("diabetes_binary_health_indicators_BRFSS2015.csv")

data<- data|>
  mutate(HighBP=factor(HighBP, levels=c(0,1),labels=c("Normal_BP","High_BP")),
         HighChol=factor(HighChol, levels=c(0,1),labels=c("Normal_Chol","High_Chol")),
         CholCheck=as.factor(CholCheck),
         Smoker=factor(Smoker,levels=c(0,1),labels=c("Non_Smoker","Smoker")),
         Stroke=factor(Stroke, levels=c(0,1),labels=c("No_Stroke","Yes_Stroke")),
         Fruits=factor(Fruits,levels=c(0,1),labels=c("No_Fruits","Eats_Fruits")),
         Veggies=factor(Veggies,levels=c(0,1),labels=c("No_Veggies","Eats_Veggies")),
         Sex=factor(Sex, level=c(0,1), labels = c("Female","Male")),
         GenHlth=factor(GenHlth,levels=c(1,2,3,4,5), 
                        labels=c("Excellent","Very Good","Good","Fair","Poor")),
         Age=factor(Age, levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                    labels=c("18-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59",
                            "60-64","65-69","70-74","75-79","80+" )),
         Education=factor(Education,levels=c(1,2,3,4,5,6),labels=c("None-K","Grades 1-8",
                                                                   "Grades 9-11","HS Diploma","Some College","Bachelor's Degree or Higher")),
         Income=factor(Income,levels=c(1,2,3,4,5,6,7,8),labels=c("<10K","<15K",
          "<20K","<25K","<35K","<50K",
          "<75K",">=75K")),
         Diabetes_binary=factor(Diabetes_binary,levels=c(0,1),labels=c("Not_Diabetic","Diabetic")),
         HeartDiseaseorAttack=factor(HeartDiseaseorAttack,levels=c(0,1),labels=c("No_Heart Disease","Heart_Disease")),
         PhysActivity=factor(PhysActivity,levels=c(0,1),labels=c("No_Physical Activity","Physical_Activity")),
         HvyAlcoholConsump=factor(HvyAlcoholConsump,levels=c(0,1),labels=c("Not_Heavy Drinker","Heavy_Drinker")),
         AnyHealthcare=factor(AnyHealthcare,levels=c(0,1),labels=c("No_Health_Coverage","Yes_Health_Coverage")),
         NoDocbcCost=factor(NoDocbcCost,levels=c(0,1),labels=c("Cost_Issue","Cost_Not_Issue")),
         DiffWalk=factor(DiffWalk,levels=c(0,1),labels=c("No_Difficulty_Walking","Difficulty_Walking"))
         )

str(data)
```

## Basic Summaries and Rates of Missing

```{r}
sum_na<-function(column){
  sum(is.na(column))
}

na_counts<-data|>
  summarize(across(everything(),sum_na))

print(na_counts)


summaries<- data|>
  summarize(across(where(is.numeric),
                   list("mean"=mean,
                         "median"=median,
                          "min"=min,
                          "max"=max,
                           "sd"=sd,
                           "iqr"=IQR),
                    .names="{.fn}_{.col}"))
print(summaries)

```


```{r}
table(data$Sex,data$Diabetes_binary)

table(data$Sex,data$Diabetes_binary,data$Age)

table(data$Education,data$HighBP)

table(data$Education,data$HighChol)

table(data$Income)

data2<-data|>
  filter( Income != ">=75K" )

table(data2$Fruits,data2$Veggies,data2$Diabetes_binary)

```


```{r}
ggplot(data=data,aes(x=Sex,fill=Diabetes_binary))+
  geom_bar(position="fill")+
  labs(x="Sex")+
  scale_fill_discrete("Diabetes Status")



ggplot(data=data|>group_by(Income),aes(x=Income,fill=Diabetes_binary))+
  geom_bar(position="fill")+
  labs(x="Income")+
  scale_fill_discrete("Diabetes Status")
```

```{r}
# Create a grouped boxplot using ggplot2
ggplot(data = data, aes(x = Education, y = BMI,
                        fill = factor(Income))) +
  geom_boxplot() +
  theme_minimal() +
  labs(fill = "Income")
```

